name: WestGate Foundation
favicon: null
layout_spectrum: 1
typography_spectrum: 0.08255905634723604
title: WestGate Foundation
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#003763'
    - '#faa519'
    - '#617e9d'
    - '#000000'
    - '#ff0000'
  brandStrength: 0.6247684590052813
  lightness: 0.186839631292969
  saturation: 0.09345869161188602
  rhythmicContrast: 0.5693715321831405
purpose: []
