name: WestGate Foundation
favicon: null
layout_spectrum: 1
typography_spectrum: 0.99147
title: WestGate Foundation
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#013763'
    - '#faa419'
    - '#557894'
    - '#d6e2e8'
  brandStrength: 0.8125
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
